# Generated by Django 2.1 on 2019-10-03 18:38

from django.db import migrations, models
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20191003_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.TextField(default='low', verbose_name=todolist.models.Priority),
        ),
    ]
