# Generated by Django 2.1 on 2019-10-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20191004_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.TextField(default='Incomplete'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
